medicator.form =
{
    "AEO":"Ätherisches Öl",
    "AMP":"Ampullen",
    "APA":"Ampullenpaare",
    "ASN":"Augen- und Nasensalbe",
    "ATO":"Augen- und Ohrentropfen",
    "ATR":"Augentropfen",
    "AUB":"Augenbad",
    "AUG":"Augengel",
    "AUS":"Augensalbe",
    "BAD":"Bad",
    "BAL":"Balsam",
    "BEU":"Beutel",
    "BON":"Bonbons",
    "BPL":"Basisplatte",
    "BTA":"Brausetabletten",
    "CRE":"Creme",
    "DFL":"Durchstechflaschen",
    "DIL":"Dilution",
    "DIS":"Depot-Injektionssuspension",
    "DOS":"Dosieraerosol",
    "DRA":"Dragees",
    "DRM":"Magensaftresistente Dragees",
    "DSC":"Dosierschaum",
    "DSS":"Dosierspray",
    "EDP":"Einzeldosis-Pipetten",
    "EIN":"Einreibung",
    "ELI":"Elixier",
    "EMU":"Emulsion",
    "ESS":"Essenz",
    "ESU":"Erwachsenen-Suppositorien",
    "EXT":"Extrakt",
    "FBE":"Filterbeutel",
    "FBW":"Franzbranntwein",
    "FER":"Fertigspritzen",
    "FET":"Fettsalbe",
    "FLA":"Flasche",
    "FLE":"Flüssigkeit zum Einnehmen",
    "FLU":"Flüssig",
    "FMR":"Magensaftresistente Filmtabletten",
    "FRB":"Beutel mit retardierten Filmtabletten",
    "FSE":"Flüssigseife",
    "FTA":"Filmtabletten",
    "GEL":"Gel",
    "GMR":"Magensaftresistentes Granulat",
    "GPA":"Gelplatte",
    "GRA":"Granulat",
    "GSE":"Granulat zur Herstellung einer Suspension zum Einnehmen",
    "GUL":"Gurgellösung",
    "HAS":"Handschuhe",
    "HKP":"Hartkapseln",
    "HPI":"Hartkapseln mit Pulver zur Inhalation",
    "HVW":"Hartkapseln mit veränderter Wirkstofffreisetzung",
    "IFA":"Infusionsampullen",
    "IFB":"Infusionsbeutel",
    "IFF":"Infusionsflaschen",
    "IFK":"Infusionslösungs-Konzentrat",
    "IFL":"Injektionsflaschen",
    "IFS":"Infusionsset",
    "IHA":"Inhalationsampullen",
    "IHP":"Inhalationspulver",
    "IIL":"Injektionslösung/Infusionslösung",
    "IKA":"Inhalationskapseln",
    "ILO":"Injektionslösung",
    "IMP":"Implantat",
    "INF":"Infusionslösung",
    "INH":"Inhalat",
    "INI":"Injektionsflaschen/Infusionsflaschen",
    "INL":"Inhalationslösung",
    "INS":"Instant-Tee",
    "IST":"Instillation",
    "ISU":"Injektionssuspension",
    "IUP":"Intrauterinpessar",
    "KAN":"Kanülen",
    "KAP":"Kapseln",
    "KAT":"Katheter",
    "KDA":"Kaudragees",
    "KEG":"Kegel",
    "KER":"Kerne",
    "KGU":"Kaugummi",
    "KKS":"Kleinkinder-Suppositorien",
    "KLI":"Klistiere",
    "KMP":"Hartkapseln mit magensaftresistent überzogenen Pellets",
    "KMR":"Magensaftresistente Kapseln",
    "KOM":"Kompressen",
    "KON":"Konzentrat",
    "KPG":"Kombipackung",
    "KSS":"Kinder- und Säuglings-Suppositorien",
    "KSU":"Kinder-Suppositorien",
    "KTA":"Kautabletten",
    "LII":"Lösung zur Injektion/Infusion/Inhalation",
    "LIQ":"Liquidum",
    "LOE":"Lösung",
    "LOT":"Lotion",
    "LSE":"Lösung zum Einnehmen",
    "LTA":"Lacktabletten",
    "LUP":"Lutschpastillen",
    "LUT":"Lutschtabletten",
    "MIL":"Milch",
    "MRG":"Magensaftresistentes Retardgranulat",
    "MTA":"Manteltabletten",
    "MUW":"Mundwasser",
    "NAG":"Nasengel",
    "NAO":"Nasenöl",
    "NAS":"Nasenspray",
    "NAW":"Wirkstoffhaltiger Nagellack",
    "NDS":"Nasendosierspray",
    "NSA":"Nasensalbe",
    "NTR":"Nasentropfen",
    "OCU":"Occusert",
    "OEL":"Öl",
    "OHT":"Ohrentropfen",
    "OVU":"Ovula",
    "PAM":"Packungsmasse",
    "PAS":"Pastillen",
    "PEL":"Pellets",
    "PEN":"Injektionslösung in einem Fertigpen",
    "PER":"Perlen",
    "PFL":"Pflaster",
    "PFT":"Pflaster-Transdermal",
    "PIF":"Pulver zur Herstellung einer Infusionslösung",
    "PIK":"Pulver zur Herstellung eines Infusionslösungskonzentrates",
    "PLE":"Pulver zur Herstellung einer Lösung zum Einnehmen",
    "PPL":"Pumplösung",
    "PSE":"Pulver zur Herstellung einer Suspension zum Einnehmen",
    "PST":"Paste",
    "PUD":"Puder",
    "PUL":"Pulver",
    "RED":"Retard-Dragees",
    "REK":"Retard-Kapseln",
    "RET":"Retard-Tabletten",
    "RGR":"Retard-Granulat",
    "RKA":"Rektalkapseln",
    "RSC":"Rektalschaum",
    "RUT":"Retard-überzogene Tabletten",
    "SAF":"Saft",
    "SAL":"Salbe",
    "SCH":"Schaum",
    "SEI":"Seife",
    "SHA":"Shampoo",
    "SIR":"Sirup",
    "SLZ":"Salz",
    "SMF":"Schmelzfilm",
    "SMT":"Schmelztabletten",
    "SMU":"Suppositorien mit Mulleinlage",
    "SPA":"Spritzampullen",
    "SPF":"Sprühflasche",
    "SPL":"Spüllösung",
    "SPR":"Spray",
    "SRI":"Spritzen",
    "SSU":"Säuglings-Suppositorien",
    "STA":"Stechampullen",
    "STB":"Stäbchen",
    "STI":"Stifte",
    "SUP":"Suppositorien",
    "SUS":"Suspension",
    "SUT":"Sublingualtabletten",
    "SUV":"Suspension für einen Vernebler",
    "SWA":"Schwämme",
    "TAB":"Tabletten",
    "TAE":"Täfelchen",
    "TAM":"Trockenampullen",
    "TEE":"Tee",
    "TEI":"Tropfen zum Einnehmen",
    "TES":"Test",
    "TIN":"Tinktur",
    "TKA":"Tabletten in Kalenderpackung",
    "TMR":"Magensaftresistente Tabletten",
    "TON":"Tonikum",
    "TPN":"Tampon",
    "TPO":"Tamponaden",
    "TRA":"Trinkampullen",
    "TRO":"Tropfen",
    "TRS":"Trockensubstanz mit Lösungsmittel",
    "TRT":"Trinktabletten",
    "TSA":"Trockensaft",
    "TSS":"Trockensubstanz ohne Lösungsmittel",
    "TTR":"Teststreifen",
    "TUB":"Tube",
    "TUE":"Tücher",
    "TUP":"Tupfer",
    "UTA":"Überzogene Tabletten",
    "VAL":"Vaginallösung",
    "VAR":"Vaginalring",
    "VCR":"Vaginalcreme",
    "VER":"Verband",
    "VGE":"Vaginalgel",
    "VKA":"Vaginalkapseln",
    "VOV":"Vaginalovula",
    "VST":"Vaginalstäbchen",
    "VSU":"Vaginalsuppositorien",
    "VTA":"Vaginaltabletten",
    "WAT":"Watte",
    "WGA":"Wundgaze",
    "WKA":"Weichkapseln",
    "WKM":"Magensaftresistente Weichkapseln",
    "WUE":"Würfel",
    "XDG":"Duschgel",
    "XGM":"Gesichtsmaske",
    "XNC":"Nachtcreme",
    "XPK":"Körperpflege",
    "XTC":"Tagescreme",
    "ZAM":"Zylinderampullen",
    "ZBU":"Zahnbürste",
    "ZGE":"Zahngel",
    "ZKA":"Zerbeisskapseln",
    "ZPA":"Zahnpasta",
    "ZZM":"Aktivität - Messung",
    "ZZW":"Aktivität - Wiegen"
};
